### ISSUE TITLE
`conda env create --name` is broken

### ISSUE THREAD

**Issue by jim22k** [conda/conda-env#105]
I want to create an environment from an existing environment.yaml file, but I want a different name for the environment than is listed in the file.

`conda env create --name custom_name` is broken and gives the following message:

    --name is deprecated. Use the following command instead:
        conda env create custom_name

Typing the recommended command doesn't work. It just does `conda env create` and completely ignores the `custom_name` argument.  I'm using conda 3.14.0.

I tried to use `conda create -n custom_name --file environment.yaml`, but that doesn't work either (see conda/conda#1360). How do I solve this problem?

**Comment by joelhullcio** [comment]
@jim22k +1
The error is introduced by conda-env 2.2.0.   Important to note that the removal of this feature BROKE CLIENT SCRIPTS AT JPM.  We need to have a strong commitment to backward compatibility.  In addition, deprecation means a feature is going to be removed in the future but it should still work.  However, why would this feature be deprecated?  This is removing valuable functionality.  Don't we want to add features to conda instead of removing them?  Please add this feature back ASAP.

**Comment by teoliphant** [comment]
@tswicegood Can you shed light on why this interface changed?

**Comment by malev** [comment]
we change it to support creating environments from anaconda.org. Working on a fix right now

**Comment by tswicegood** [comment]
@teoliphant the interface was changed to decrease the friction for creating a remote environment.  Writing out `conda env create --name tswicegood/foobar` seems off.  The intent here was to deprecate `--name`, not remove its functionality.  That was a regression as it was supposed to only display the warning that it was no longer the proper way, but would still work.

**Comment by malev** [comment]
The fix has been merged, waiting the anaconda team to proceed with the release of `2.2.3`. I'm hoping tmr it will be done.

**Comment by malev** [comment]
@jim22k could you update your `conda-env` and try again?

**Comment by jim22k** [comment]
Just tried with conda-env v2.2.3 and it works. Thanks for the fast turnaround.
