### ISSUE TITLE
activate should export an environment variable with the full path to the environment

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-env#63]
I've had a couple people request this. `CONDA_DEFAULT_ENV` is not what they want because they want a full path.

**Comment by asmeurer** [comment]
Alternately, we should add `conda info --default-env`. Parsing `conda info --json` is not something people should be doing from the shell.

**Comment by tswicegood** [comment]
Hmm.  I can see both options as a good way to do this.  Having an environment variable is nice as it's available all sub-processes as well, though.  What to call it is the question.  At first pass, `CONDA_CURRENT_PREFIX` comes to mind.

I'd prefer not to use `DEFAULT` in the name because no matter how technically correct, it's confusing.  There's certain baggage that comes along with that word.

**Comment by bkreider** [comment]
I have a good use case for this.  The openssl commands i put into FD last week.  I'd like to do something like this for non-python binaries that have data in the $PREFIX:
```
openssl s_client -connect store.continuum.io:443 -CAfile $PREFIX/ssl/cacert.pem
```

**Comment by tdhopper** [comment]
@tswicegood: `default` would be consistent with the existing `CONDA_DEFAULT_ENV` and `conda info --default-prefix`.

**Comment by tswicegood** [comment]
@tdhopper yeah -- what this should be is something more like `VIRTUAL_ENV`.  We might even simply do `CONDA_ENV`.  Actually, thinking along those lines, how about `CONDA_ENV_PATH`?

---

Regarding the use of default, I hope to start phasing it out.  I've yet to meet any developer who wasn't confused by it because the term has so much implicit meaning.  If you know the technical implementation of Conda, it starts to make sense, but users shouldn't have to understand every detail about Conda in order to be proficient and make mental models about what it is doing.

Not to worry, though.  No plans on removing it any time soon.

**Comment by tdhopper** [comment]
I like `CONDA_ENV_PATH`.

**Comment by malev** [comment]
We already have `CONDA_ENV_PATH` working everywhere but windows.
There is a patch coming for windows #139

**Comment by ijstokes** [comment]
I'm worried there is something broken with this functionality.  Notice how `$CONDA_ENV_PATH` is totally confused through the sequence of operations I do below:

```bash
(sparkkernel)ijstokes@petawawa sbt-deps $ conda --version
conda 3.15.1
(sparkkernel)ijstokes@petawawa sbt-deps $ env | grep -i conda
PATH=/Users/ijstokes/anaconda/envs/sparkkernel/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin
CONDA_ENV_PATH=/Users/ijstokes/anaconda
CONDA_DEFAULT_ENV=sparkkernel
(sparkkernel)ijstokes@petawawa sbt-deps $ source activate root
discarding /Users/ijstokes/anaconda/envs/sparkkernel/bin from PATH
prepending /Users/ijstokes/anaconda/bin to PATH
(root)ijstokes@petawawa sbt-deps $ env | grep -i conda
PATH=/Users/ijstokes/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin
CONDA_ENV_PATH=/Users/ijstokes/anaconda/envs/sparkkernel
CONDA_DEFAULT_ENV=root
(root)ijstokes@petawawa sbt-deps $ source activate sparkkernel
discarding /Users/ijstokes/anaconda/bin from PATH
prepending /Users/ijstokes/anaconda/envs/sparkkernel/bin to PATH
(sparkkernel)ijstokes@petawawa sbt-deps $ env | grep -i conda
PATH=/Users/ijstokes/anaconda/envs/sparkkernel/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin
CONDA_ENV_PATH=/Users/ijstokes/anaconda
CONDA_DEFAULT_ENV=sparkkernel
```

**Comment by malev** [comment]
`CONDA_DEFAULT_ENV` should be working on 2.4.0
